### PR TITLE
Modernize code to use python 3 syntax

### PR DESCRIPTION
**Pull request by benabel**
This PR is related #110. As python 2.7 comes to end of life in 2020, switching to python 3 seems meaningful.

For this, I've used `future` module to port code to python 3 syntax so this *PR adds a dependence to future for python 2 users*.

## Task list:

- [x] Port code to python 3 and handle regression to python 2 with a dependencie on `future`
- [x] Test with pytest and tox locally on python 2.7 and 3.8.
- [x] Lint and test on CI with github tasks on ubuntu, macos and windows with python 2.7 and python 3.5 -> 3.8.
- [x] Fix warnings and errors from flake8.
- [x] Fix setup.py to use `future` on python 2.7.
- [x] Use README.rst as the long description on `setup.py`.
- [x] Build wheels packages with tox.
- [ ] This PR drop langage support for python<2.7, @lebigot you should add a note on docs to indicate which version should be installed to support python<2.7.
- [ ] Changelog now in README hasn't been updated.

@lebigot Every tests passes, so I remove the WIP badge. This PR can now be merged. You can see the build jobs on the actions of my repo: 

Sans titre

### CODE REVIEW

**Comment by BishopWolf** [comment]
Any news on this?

**Comment by BishopWolf** [comment]
I am still not able to use this package, any news on when this will be integrated?

**Comment by lebigot** [comment]
I am sorry for that. My baby has been keeping me busy. Adding wheels to uncertainties is my top personal project starting this week, so I hope to review and integrate this pull request in the next couple of weekends.

**Comment by BishopWolf** [comment]
Sorry for being pedantic but, is there any news on this?

**Comment by lebigot** [comment]
I am looking into this pull request. It contains many different things (wheels instead of eggs, new testing system, lint changes, move to Python 3 and future, etc.) that require some individual attention, so it's taking me some time. Doing my best given how busy I am with my baby. :)

**Comment by benabel** [comment]
@lebigot take your time, I think every thing is Ok. Let me know if you have some remarks.

**Comment by ep12** [comment]
One thing I noted is that the version number in this commit is (3, 1, 2) instead of (3, 1, 3)
Short summary so that @lebigot does not have to scroll through code style commits...
@lebigot : The following commits seem fine, so you don't have to spend too much time on reviewing them.
+ 128fe0f08: setup.py changes, looks good
+ 51efe9f6: updated readme, setup.py now reads the readme file.
+ c03e056: codestyle + import pytest, wraps two blocks using pytest functions
+ All the **LINT** commits are okay, no changes except a better code style
That means 6 of 18 files contain the important functional changes..

**Comment by MichaelTiemannOSC** [comment]
Time to revive?

**Comment by lebigot** [comment]
It's an important pull request, so it's always a good time to revive it. :) I must say that this project is not at the top of my priority list, even though I like it and think it should keep improving if needed (there are some current areas of improvement, such as this full migration to Python 3 and a more modern handling of arrays/dataframes of numbers with uncertainties).

**Comment by wshanks** [comment]
Given that this PR has sat unmerged for three years, I think the best course of action for making progress on doing what it is trying to do is to break it up into smaller pieces that are easier to review. The items in the task list all sound nice to me, but they don't necessarily all need to be merged together. I am not volunteering to do the work, so others can make their own decisions :slightly_smiling_face:

I ended up here trying to figure out which of my dependencies was pulling in `future` which has a CVE opened against it. I would say that Python 2 support is not something many users are looking for in new releases now, so the `future` dependency and Python 2 support could probably be dropped.

**Comment by benabel** [comment]
It's too late to revive this a new PR should ne opened.

**Pull request closed without merging**
