### PR TITLE
R flags

### PR DESCRIPTION
**Pull request by ep12**
See #113.

### CODE REVIEW

**Comment by lebigot** [comment]
I would have a few fixes and improvements to make. Apparently, you could allow me to push to this specific pull request branch: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork. Can you enable this?
Otherwise, I can always import locally your r-flags branch, update it and then merge it back to master, but this pull request would have to be closed without appearing to ever have been merged.

**Comment by ep12** [comment]
Just in case you missed it: I enabled the editing so that you can change the code to your liking.

**Comment by lebigot** [comment]
I have been working on this here and there. Here are some highlights of my changes so far:
- Switch from an r/R formatting flag to a p (parentheses) flag.
- Fixed inconsistencies between b/B and r/R flags (both were used).
- Fixed bug with print('{:.1u%p}'.format(x)): spurious second parenthesis.
- Better doc.

Working branch: https://github.com/lebigot/uncertainties/tree/ep12_r-flags (I saw your message about the access rights on your fork only after starting working on a local branch).

There are still parts of the code that I need to proofread (notably the tests).

**Comment by lebigot** [comment]
I kept checking the changes and updated a few more things:
- Fixed bug with "  (2+/-1)  " not being parsed by `ufloat_fromstr()` (contrary to what the documentation claimed).
- Added a test for the bug above.
- Moved some new code and doc where they belong (parsing done inside the existing parsing function instead of outside, detailed documentation for the formats in the more user-facing `AffineScalarFunc.__format__()`, etc.).
- Removed duplicated documentation for the new "p" formatting option (it's still duplicated between the detailed web user guide and the docstrings, but that's expected).

**Pull request merged**
