### PR TITLE
Adding "voluntary donations" link to the readme.

### PR DESCRIPTION
**Pull request by AdityaSavara**
@lebigot 

Donations link added to the read me. I have tried to use wording that is nice and hopefully effective. I have also checked that the rst syntax worked correctly for how it is displayed on github.

You can see how it looks here: https://github.com/AdityaSavara/uncertainties/tree/patch-1

### CODE REVIEW

**Comment by AdityaSavara** [comment]
@lebigot  I'm not sure if you saw this, I've made the pull request about adding the donations link to the readme. The pull request has a link to my branch to show you how this edit appears. You may want to change the text, if you'd like.

**Comment by lebigot** [comment]
Yes, thanks. I'll have a look very soon. My days and evenings are filled with emergencies right now, but that won't be in a long time.

**Review by lebigot — CHANGES_REQUESTED** [review]
Thanks!

How about the following version?

```
Voluntary donations
-------------------

If you find this open-source software useful (e.g. in saving you time or helping you produce
something valuable), please `consider donating $10 or more to help the creator <https://www.paypal.com/donate/?cmd=_s-xclick&hosted_button_id=4TK7KNDTEDT4S>`_.
```

**Comment by AdityaSavara** [comment]
I think that your suggested change is fine and have implemented it:
https://github.com/AdityaSavara/uncertainties/tree/patch-1

I do wonder if it would better to change the text to "please consider donating to help contribute to maintenance of the package."  

I think that this new suggested text would be better. If you like it, I'll make the change. Otherwise you can merge as is.

**Comment by lebigot** [comment]
Thanks.

I was wondering the same thing. I like your suggestion. Please just add "the" before "maintenance". :)

**Comment by AdityaSavara** [comment]
I have added the new wording:
https://github.com/AdityaSavara/uncertainties/blob/patch-1/README.rst

**Comment by lebigot** [comment]
Let me merge this. Thank you!

**Pull request merged**
